Feature/13 initial formik implementation
akvo/nmis-mobile pull request #19
Opened 2023-06-22 11:00 UTC by wayangalihpratama

### TODO/DONE:

---

- [x] Form Layout
- [x] Form Group Navigation
- [x] Field Group Header
- [x] Field Label
- [ ] Component test case

**Field Type**
- [x] Input Field
- [x] Number Field
- [x] TextArea Field
- [x] DatePicker Field
- [x] Radio Field
- [x] Checkbox Field
- [x] Single select dropdown Field
- [x] Multiple select dropdown Field
- [x] Image Field

2023-06-23 04:46 UTC, dedenbangkit requested changes
- Where is the [JSON mapping ](https://app.asana.com/0/1204809698735754/1204858620492679/f)function?
- The next and previous button are not fixed yet, it still has gap with the middle layer.
- Please test: what we are expected from submit button

2023-06-27 10:16 UTC, dedenbangkit requested changes
Hi @wayangalihpratama, please move test to the folder which component test are belong to. Look at store tests: as an example.

2023-06-27 12:56 UTC, wayangalihpratama commented
> Hi @wayangalihpratama, please move test to the folder which component test are belong to. Look at store tests: as an example.

Hi mas @dedenbangkit , I have moved the test into each folder inside form component folder.

2023-06-28 01:23 UTC, dedenbangkit approved these changes

2023-06-28 01:23 UTC, merged