Feature/23 app preference page
akvo/nmis-mobile pull request #25
Opened 2023-06-26 14:46 UTC by ifirmawan

2023-06-29 01:59 UTC, dedenbangkit requested changes

2023-06-29 01:59 UTC, dedenbangkit commented on app/src/pages/FormAction.js
Why did you change the form related component @ifirmawan, have you inform @wayangalihpratama ?

2023-06-29 01:59 UTC, dedenbangkit commented on app/__tests__/pages/Settings.test.js
Move this to src/pages/__test__

2023-06-29 01:59 UTC, dedenbangkit commented on app/__tests__/components/Stack.test.js
Move this please

2023-06-29 01:59 UTC, dedenbangkit commented on app/__tests__/components/BaseLayout/BaseLayout.test.js
Move this

2023-06-29 01:59 UTC, dedenbangkit commented on app/__tests__/components/BaseLayout/PageTitle.test.js
Move this

2023-06-29 01:59 UTC, dedenbangkit commented on app/__tests__/components/CenterLayout/Titles.test.js
Move this

2023-06-29 02:31 UTC, wayangalihpratama commented on app/src/pages/FormAction.js
Hi mas @dedenbangkit, this `FormAction.js` is not related to the form container component.

2023-06-29 02:35 UTC, dedenbangkit commented on app/src/pages/FormAction.js
What are these @ifirmawan ? Can we think other different name

2023-06-29 03:15 UTC, ifirmawan commented on app/src/pages/FormAction.js
This is the second Page of this design mas @dedenbangkit 
https://wiki.cloud.akvo.org/uploads/images/gallery/2023-06/ajxAGZ8HNQ7J4kuz-01-nmis-layout-base.png
My first assumption FormAction is a page displaying a list of actions

But, I'll try to think another name

2023-06-29 07:01 UTC, ifirmawan commented on app/src/pages/FormAction.js
based on ChatGPT suggestion I'll rename it "ManageForm"

2023-07-02 23:42 UTC, dedenbangkit approved these changes

2023-07-02 23:43 UTC, merged