Feature/31 geolocation question type
akvo/nmis-mobile pull request #34
Opened 2023-07-03 13:43 UTC by ifirmawan

## TODO/DONE

- [x] Get the location
- [x] Map Preview
- [ ] Unit tests

2023-07-04 11:45 UTC, ifirmawan commented
Hi mas @dedenbangkit  I'll update the unit tests in a separate PR. Thank you

2023-07-04 12:15 UTC, dedenbangkit requested changes
Hi @ifirmawan please don't use `React.*` directly

2023-07-04 12:15 UTC, dedenbangkit commented on app/src/navigation/index.js
Where is the test for MapViewPage component?

2023-07-04 12:15 UTC, dedenbangkit commented on app/src/pages/MapView.js
> +  const [htmlContent, setHtmlContent] = React.useState(null);
useState

2023-07-04 12:15 UTC, dedenbangkit commented on app/src/pages/MapView.js
> +import React from 'react';
```jsx
import React, { useState, useRef, useEffect } from 'react';
```

2023-07-04 12:15 UTC, dedenbangkit commented on app/src/pages/MapView.js
> +  const webViewRef = React.useRef(null);
useRef

2023-07-04 12:15 UTC, dedenbangkit commented on app/src/pages/MapView.js
> +  React.useEffect(() => {
useEffect

2023-07-04 12:15 UTC, dedenbangkit commented on app/src/pages/MapView.js
> +  React.useEffect(() => {
useEffect

2023-07-04 12:15 UTC, dedenbangkit commented on app/src/form/FormContainer.js
>    const formRef = React.useRef();
useRef

2023-07-04 12:15 UTC, dedenbangkit commented on app/src/form/components/QuestionField.js
QuestionField with TypeGeo test

2023-07-04 12:15 UTC, dedenbangkit commented on app/src/form/fields/TypeGeo.js
> +      <View style={styles?.inputGeoContainer}>
why `styles?.inputGeoContainer` and not `styles.inputGeoContainer`?

2023-07-04 12:22 UTC, ifirmawan commented on app/src/navigation/index.js
Actually, I'll make it in the next PR mas and I'll try to increase the coverage

2023-07-04 14:17 UTC, ifirmawan commented on app/src/navigation/index.js
If I just make a snapshot it looks like this, 
![Screenshot_20230704_211623](https://github.com/akvo/nmis-mobile/assets/20871229/9f6a1166-1aa2-4536-a7ac-918e35e7de53)

so it's taking me some time to sort it out

2023-07-05 04:27 UTC, dedenbangkit approved these changes

2023-07-05 04:28 UTC, merged